<?php
require_once 'ConnecttionInfo.php';



function my_forms_menu()
{

    $items['learn/form-api'] = array(
        'title' => t('Form API'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('first_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function first_form()
{
    $form['name'] = array(
        '#title' => t('Your name'),
        '#type' => 'textfield',
        '#description' => t('Please enter your name'),
    );

    $form['email'] = array(
        '#title' => t('Your E-mail'),
        '#type' => 'textfield',
        '#description' => t('Please enter your email'),
    );

    $form['submit'] =array(
        '#type' => 'submit',
        '#value' => t('Send'),
    );

   // $form['#validate'][] = 'validate_name';

    return $form;
}

function first_form_validate($form,$form_state)
{
    if(!preg_match("`[aA-zZ0-9]*@[a-z0-9]*\\.[a-z]*`",$form_state['values']['email'])) {
        form_set_error("email", $form_state['values']['email'] . " - is not email");
    }
    else
    {



        global $mysqli;
        $result = $mysqli->query("INSERT INTO mytable (`name`,`email`) VALUES('{$form_state['values']['name']}','{$form_state['values']['email']}')");

        if ($result) {
            drupal_set_message("Good");
        } else {
            drupal_set_message("Bad");
        }
    }



}


?>