<?php
    function new_post_help($path,$arg)
    {
        switch($path)
        {
            case "admin/help#new_post":
        return '<p>'.t("123").'</p>';
             break;
        }
    }

    function new_post_block_info()
    {
        $blocks['new_post'] = array(
            'info' => t('New post'),
            'cache' => DRUPAL_CACHE_PER_ROLE,
        );
        return $blocks;
    }

    function new_post_contents()
    {
        $today = getdate();
        $start_time = mktime(0,
            0,
            0,
            $today['mon'],
            ($today['mday']-7),
            $today['year']
            );
        $end_time = time();

        $query =db_select('node','n')
            ->fields('n',array('nid','title','created'))
            ->condition('status',1)
            ->condition('created',array($start_time,$end_time),'BETWEEN')
            ->orderBy('created','DESC')
            ->execute();
        return $query;
    }

    function new_post_block_view($delta="")
    {
        switch($delta)
        {
            case 'new_post':
                $block['subject'] = t('Новое на сайте');
                if(user_access('access content'))
                {
                    $result = new_post_contents();
                    $items[] = array();
                    foreach ($result as $node)
                    {
                        $items[] = array(

                            'data' => l($node->title,'node/'.$node->nid),
                        );
                    }
                    if(empty($items))
                    {
                        $block['content'] = t('За последнюю неделю ничего нет.');
                    }
                    else
                    {
                        $block['content'] = theme('item_list',array('items' => $items));
                    }

                }
                return $block;
        }
    }
